### ISSUE TITLE
怎么连接车debug

### ISSUE THREAD

**Issue by purespike** [ChenqiaoStation/net.cctv3.iQinCarPlayer#1]
你好朋友，问问你是怎么用电脑连车子debug的？
我的数据线连上咋没有反应呢

**Comment by ChenqiaoStation** [comment]
> 你好朋友，问问你是怎么用电脑连车子debug的？ 我的数据线连上咋没有反应呢

我的是秦Pro DM，这货本质上就是个android机子，你先在手机上面调试，调试个差不多了，然后车机里面安装一个钉钉，把apk发车机的钉钉上，然后下载安装。
